// music-tagger-frontend/src/app/features/plan-review/operation-card/operation-card.component.ts
import { Component, input, output } from '@angular/core';
import { MatCardModule } from '@angular/material/card';
import { MatChipsModule } from '@angular/material/chips';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatTooltipModule } from '@angular/material/tooltip';
import { TagOperation, OperationStatus } from '../../../models/types';

@Component({
  selector: 'app-operation-card',
  standalone: true,
  imports: [MatCardModule, MatChipsModule, MatButtonModule, MatIconModule, MatTooltipModule],
  template: `
    <mat-card class="op-card">
      <mat-card-header>
        <mat-card-title class="filename">{{ filename() }}</mat-card-title>
        <mat-chip [class]="'status-' + operation().status.toLowerCase()" class="status-chip">
          {{ operation().status }}
        </mat-chip>
      </mat-card-header>
      <mat-card-content>
        <div class="diff-table">
          <div class="diff-header">
            <span>Tag</span>
            <span>Actuel</span>
            <span>Suggere</span>
          </div>
          @for (entry of allTags(); track entry.key) {
            <div class="diff-row" [class.changed]="entry.current !== entry.suggested">
              <span class="tag-name">{{ entry.key }}</span>
              <span class="old-value">{{ entry.current || '—' }}</span>
              <span class="new-value">{{ entry.suggested || '—' }}</span>
            </div>
          }
        </div>
        @if (operation().message) {
          <p class="message">{{ operation().message }}</p>
        }
      </mat-card-content>
      @if (operation().status === 'PENDING') {
        <mat-card-actions align="end">
          <button mat-button color="warn" (click)="rejected.emit(operation().filepath)"
                  matTooltip="Rejeter cette operation">
            <mat-icon>close</mat-icon> Rejeter
          </button>
          <button mat-flat-button (click)="approved.emit(operation().filepath)"
                  matTooltip="Approuver cette operation">
            <mat-icon>check</mat-icon> Approuver
          </button>
        </mat-card-actions>
      }
    </mat-card>
  `,
  styles: `
    .op-card {
      margin-bottom: 8px;
    }
    mat-card-header {
      display: flex;
      align-items: center;
      justify-content: space-between;
    }
    .filename {
      font-size: 0.9rem;
      font-family: monospace;
      overflow: hidden;
      text-overflow: ellipsis;
      white-space: nowrap;
      max-width: 400px;
    }
    .status-chip {
      font-size: 0.75rem;
    }
    .diff-table {
      display: grid;
      grid-template-columns: 120px 1fr 1fr;
      gap: 4px 12px;
      font-size: 0.85rem;
      margin: 12px 0;
    }
    .diff-header {
      display: contents;
      span {
        font-weight: 600;
        color: var(--mat-sys-on-surface-variant);
        text-transform: uppercase;
        font-size: 0.7rem;
        letter-spacing: 0.05em;
        padding-bottom: 4px;
        border-bottom: 1px solid var(--mat-sys-outline-variant);
      }
    }
    .diff-row {
      display: contents;
    }
    .tag-name {
      font-weight: 500;
    }
    .old-value {
      color: var(--mat-sys-on-surface-variant);
    }
    .changed .old-value {
      color: #f44336;
      text-decoration: line-through;
    }
    .changed .new-value {
      color: #4caf50;
      font-weight: 500;
    }
    .message {
      font-size: 0.8rem;
      color: var(--mat-sys-on-surface-variant);
      font-style: italic;
    }
    .status-pending { --mat-chip-label-text-color: #ff9800; }
    .status-approved { --mat-chip-label-text-color: #4caf50; }
    .status-rejected { --mat-chip-label-text-color: #f44336; }
    .status-applied { --mat-chip-label-text-color: #66bb6a; }
    .status-failed { --mat-chip-label-text-color: #f44336; }
  `,
})
/**
 * Carte d'une operation de tagging — affiche le diff (tags actuels vs suggeres)
 * et les boutons approuver/rejeter quand l'operation est PENDING.
 */
export class OperationCardComponent {
  readonly operation = input.required<TagOperation>();
  readonly approved = output<string>();
  readonly rejected = output<string>();

  filename(): string {
    const fp = this.operation().filepath;
    return fp.split(/[/\\]/).pop() || fp;
  }

  /** Fusionne les cles de currentTags et suggestedTags pour afficher le diff complet. */
  allTags(): { key: string; current: string; suggested: string }[] {
    const op = this.operation();
    const keys = new Set([...Object.keys(op.currentTags), ...Object.keys(op.suggestedTags)]);
    return [...keys].map(key => ({
      key,
      current: op.currentTags[key] || '',
      suggested: op.suggestedTags[key] || '',
    }));
  }
}

// music-tagger-ui/src/components/plan/OperationCard.tsx
import { useMemo } from 'react';
import Card from '@mui/material/Card';
import CardContent from '@mui/material/CardContent';
import CardActions from '@mui/material/CardActions';
import Button from '@mui/material/Button';
import Chip from '@mui/material/Chip';
import Typography from '@mui/material/Typography';
import Box from '@mui/material/Box';
import Table from '@mui/material/Table';
import TableBody from '@mui/material/TableBody';
import TableCell from '@mui/material/TableCell';
import TableHead from '@mui/material/TableHead';
import TableRow from '@mui/material/TableRow';
import type { TagOperation } from '../../types/types';
import { OperationStatus } from '../../types/types';
import { extractFilename } from '../../utils/helpers';

interface Props {
  operation: TagOperation;
  onApprove: (filepath: string) => void;
  onReject: (filepath: string) => void;
}

/**
 * Carte d'une opération de tagging dans la page de revue d'un plan.
 * Affiche un tableau comparatif (tags actuels vs suggérés) avec mise en évidence
 * des différences (barré rouge pour l'ancien, gras vert pour le nouveau).
 * Le chip de statut (PENDING/APPROVED/REJECTED/APPLIED/FAILED) est coloré.
 * Les boutons Approuver/Rejeter ne sont visibles que pour les opérations en attente (PENDING).
 */
export default function OperationCard({ operation, onApprove, onReject }: Props) {
  // Fusionne les clés de tags actuels et suggérés pour afficher toutes les lignes du diff
  const allTags = useMemo(() => {
    const keys = new Set([
      ...Object.keys(operation.currentTags),
      ...Object.keys(operation.suggestedTags),
    ]);
    return Array.from(keys).sort();
  }, [operation]);

  const isPending = operation.status === OperationStatus.PENDING;

  /** Mapping statut → couleur MUI pour le Chip. */
  const statusColor: Record<string, 'default' | 'primary' | 'error' | 'success' | 'warning'> = {
    PENDING: 'default',
    APPROVED: 'primary',
    REJECTED: 'error',
    APPLIED: 'success',
    FAILED: 'warning',
  };

  return (
    <Card variant="outlined" sx={{ mb: 1 }}>
      <CardContent sx={{ pb: 1 }}>
        <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 1 }}>
          <Typography variant="subtitle2">{extractFilename(operation.filepath)}</Typography>
          <Chip label={operation.status} color={statusColor[operation.status] ?? 'default'} size="small" />
        </Box>

        <Table size="small">
          <TableHead>
            <TableRow>
              <TableCell sx={{ fontWeight: 600 }}>Tag</TableCell>
              <TableCell sx={{ fontWeight: 600 }}>Actuel</TableCell>
              <TableCell sx={{ fontWeight: 600 }}>Suggere</TableCell>
            </TableRow>
          </TableHead>
          <TableBody>
            {allTags.map((tag) => {
              const current = operation.currentTags[tag] ?? '';
              const suggested = operation.suggestedTags[tag] ?? '';
              const changed = current !== suggested;
              return (
                <TableRow key={tag}>
                  <TableCell>{tag}</TableCell>
                  <TableCell
                    sx={changed ? { textDecoration: 'line-through', color: 'error.main' } : {}}
                  >
                    {current || '-'}
                  </TableCell>
                  <TableCell sx={changed ? { fontWeight: 600, color: 'success.main' } : {}}>
                    {suggested || '-'}
                  </TableCell>
                </TableRow>
              );
            })}
          </TableBody>
        </Table>

        {operation.message && (
          <Typography variant="caption" color="text.secondary" sx={{ mt: 1, display: 'block' }}>
            {operation.message}
          </Typography>
        )}
      </CardContent>

      {isPending && (
        <CardActions sx={{ justifyContent: 'flex-end' }}>
          <Button size="small" color="error" onClick={() => onReject(operation.filepath)}>
            Rejeter
          </Button>
          <Button size="small" variant="contained" onClick={() => onApprove(operation.filepath)}>
            Approuver
          </Button>
        </CardActions>
      )}
    </Card>
  );
}
